import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import TemplateWrapper from "./TemplateWrapper";
import Hide_footer from "./Hide_footer"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TemplateWrapper>
          <Hide_footer>
          <main className="min-h-screen max-[700px]:min-h-auto overflow-hidden">
            {children}
          </main>
          </Hide_footer>
        </TemplateWrapper>

      </body>
    </html>
  );
}
